spring:
  application:
    name: Inventory-Management-System
  datasource:
    url: jdbc:h2:file:./data/InventoryDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0
  port: 8082

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
